service: doxa-etl-crawler

custom:
  awsRegion: ${file(./serverless-config/env/env.${opt:stage}.yml):awsRegion}
  awsAccount: ${file(./serverless-config/env/env.${opt:stage}.yml):awsAccount}
  role: arn:aws:iam::${self:custom.awsAccount}:role/lambda-basic-execution

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs10.x
  timeout: 300
  region: ${self:custom.awsRegion}
  versionFunctions: false
  role: ${self:custom.role}

functions:
  doxa-etl-crawler-com01:
    name: doxa-etl-crawler-com01-${opt:stage}
    timeout: 300
    handler: dynamic365/index.handler
    events:
      - schedule: rate(24 hours)
    environment:
      BUCKET_NAME: doxa-etl
      COMPANY_NAME: com1
      API_ENDPOINT: https://jsonplaceholder.typicode.com/todos
      API_TYPE: dynamic365

  doxa-etl-crawler-com02:
    name: doxa-etl-crawler-com02-${opt:stage}
    timeout: 300
    handler: dynamic365/index.handler
    events:
      - schedule: rate(24 hours)
    environment:
      BUCKET_NAME: doxa-etl
      COMPANY_NAME: com2
      API_ENDPOINT: https://jsonplaceholder.typicode.com/todos
      API_TYPE: dynamic365
