service: doxa-etl-crawler

custom:
  awsRegion: ${file(./serverless-config/env/env.${opt:stage}.yml):awsRegion}
  awsAccount: ${file(./serverless-config/env/env.${opt:stage}.yml):awsAccount}
  role: arn:aws:iam::${self:custom.awsAccount}:role/lambda-basic-execution

provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs10.x
  timeout: 300
  region: ${self:custom.awsRegion}
  versionFunctions: false
  role: ${self:custom.role}

functions:
  doxa-etl-crawler-com01:
    name: doxa-etl-crawler-com01-${opt:stage}
    timeout: 300
    handler: com01/index.handler
    events:
      - schedule: rate(10 minutes)
    environment:
      BUCKET_NAME: ${file(./serverless-config/env/env.${opt:stage}.yml):environment.BUCKET_NAME}
  doxa-etl-crawler-com02:
    name: doxa-etl-crawler-com02-${opt:stage}
    timeout: 300
    handler: com02/index.handler
    events:
      - schedule: rate(10 minutes)
    environment:
      BUCKET_NAME: ${file(./serverless-config/env/env.${opt:stage}.yml):environment.BUCKET_NAME}
